#!/bin/bash -e

export GOPATH=${PWD}/gopath

rm -rf $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go get github.com/codegangsta/cli
go get github.com/ryanuber/columnize

SHA=`git rev-parse HEAD`
go build -o bin/runadock -ldflags "-X main.revision $SHA" .
